"use client";

import { useEffect, useMemo, useState, type ReactNode } from "react";
import { StatusBadge } from "@/components/StatusBadge";
import { calculateBudget, overheadApplies, programTypeParameters } from "@/lib/calculations/budget-engine";
import { detectPotentialDuplicateCosts } from "@/lib/calculations/consolidation";
import { formatCLP, formatPercent } from "@/lib/calculations/currency";
import { getActivePeriods } from "@/lib/calculations/periods";
import type { AccessRole, BudgetItem, BudgetTemplate, CohortBudget, CohortDiscount, ExternalIncome, Program, ReviewDecision, SemesterParameters } from "@/lib/calculations/types";
import { demoBudgets, institutionalParameters, programs as demoPrograms } from "@/lib/demo-data";
import { downloadBudgetPdf, downloadBudgetXlsx } from "@/lib/export/download";
import { applyBudgetTemplate } from "@/lib/templates/apply-template";
import { defaultBudgetTemplates } from "@/lib/templates/default-templates";
import { applyWorkflowAction, availableWorkflowActions, canDeleteBudget, canEditBudget, type WorkflowAction } from "@/lib/workflow/budget-workflow";

const STORAGE_KEY = "utem-postgrado-budgets-v5";
const TEMPLATE_STORAGE_KEY = "utem-postgrado-budget-templates-v5";
const ROLE_KEY = "utem-postgrado-active-role";
const COST_CATEGORIES: BudgetItem["category"][] = ["Honorarios académicos","Honorarios no académicos","Dirección","Asistencia","Gastos operacionales","Software","Difusión","Congresos","Pasantías","Becas de manutención","Bienes y servicios","Libros y publicaciones","Pasajes y fletes","Viáticos","Otros"];
const INCOME_TYPES: ExternalIncome["type"][] = ["Beca ANID","Otra beca externa","Convenio","Aporte institucional","Proyecto","Donación","Ingreso extraordinario","Otro"];

type ApiIdentity = { userId: string; email: string; name: string; roles: AccessRole[] };
type ApiTuition = { year: number; amount: string | number; source: "PROPIO" | "PLANTILLA_DOCTORADO" };
type ApiProgram = { id: string; code: string; name: string; type: Program["type"]; faculty: string; director: string; officialDurationSemesters: number; status: "ACTIVO" | "INACTIVO" | "EN_DISENO"; costCenter?: string | null; annualTuitions?: ApiTuition[] };
type ApiBudgetRecord = { id: string; program: ApiProgram; cohortName: string; startYear: number; startSemester: 1 | 2; durationSemesters: number; initialStudents: number; status: string; workflowStage: CohortBudget["workflowStage"]; facultyOverheadRate: string | number; enrollmentRecognitionRate: string | number; authorizedInitialCarryover: string | number; includeAuthorizedCarryover?: boolean; normalizeSharedCosts?: boolean; alertPotentialDuplicates?: boolean; appliedTemplateId?: string | null; appliedTemplateVersion?: number | null; appliedTemplate?: { code?: string } | null; responsible?: { name: string }; createdAt: string; updatedAt?: string; notes?: string | null; semesterPeriods?: Array<{ year: number; semester: 1 | 2; position: number; parameters?: Record<string, unknown> | null }>; discounts?: Array<Record<string, unknown>>; externalIncome?: Array<Record<string, unknown>>; items?: Array<Record<string, unknown>>; versions?: Array<{ number: number }>; workflowEvents?: Array<{ id: string; role: AccessRole; action: string; fromStage: CohortBudget["workflowStage"]; toStage: CohortBudget["workflowStage"]; comment?: string | null; createdAt: string; user?: { name: string } }> };
type ApiTemplate = Omit<BudgetTemplate, "description"> & { description?: string | null };

const numberValue = (value: unknown) => Number.isFinite(Number(value)) ? Number(value) : 0;
const clone = <T,>(value: T): T => structuredClone(value);
const uid = (prefix: string) => `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`;
const budgetStatus = (value: string): CohortBudget["status"] => ({ BORRADOR: "Borrador", EN_REVISION: "En revisión", OBSERVADO: "Observado", APROBADO: "Aprobado", REEMPLAZADO: "Reemplazado" } as Record<string,CohortBudget["status"]>)[value] ?? "Borrador";
const workflowDecision = (action: string): ReviewDecision => ({ SUBMIT_VB: "ENVIADO", VB_APPROVE: "VISTO_BUENO", VB_OBSERVE: "OBSERVADO", FINAL_APPROVE: "APROBADO", FINAL_OBSERVE: "RECHAZADO" } as Record<string,ReviewDecision>)[action] ?? "OBSERVADO";
const responseBody = async <T,>(response: Response): Promise<T> => { const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error((body as { error?: string }).error ?? "No fue posible completar la operación."); return body as T; };

function toProgram(record: ApiProgram): Program {
  const annualTuition = Object.fromEntries((record.annualTuitions ?? []).map((item) => [item.year, numberValue(item.amount)]));
  return { id: record.id, code: record.code, name: record.name, type: record.type, faculty: record.faculty, director: record.director, officialDurationSemesters: record.officialDurationSemesters, status: record.status === "ACTIVO" ? "Activo" : record.status === "INACTIVO" ? "Inactivo" : "En diseño", costCenter: record.costCenter ?? undefined, annualTuition, tuitionSource: record.annualTuitions?.some((item) => item.source === "PROPIO") ? "PROPIO" : "PLANTILLA_DOCTORADO" };
}
function emptySemester(year: number, semester: 1 | 2, students = 0): SemesterParameters { return { year, semester, activeStudents: students, graduatingStudents: 0, directTeachingHours: 0, replacementTeachingHours: 0, electiveSubjects: 0, electiveSections: 0, specializedCourses: 0, specializedSections: 0, internalTuitionScholarshipStudents: 0, internalTuitionScholarshipCoverage: 1, maintenanceScholarshipStudents: 0, maintenanceScholarshipMonths: 0, notes: "" }; }
function toBudget(record: ApiBudgetRecord): CohortBudget {
  const semesters = (record.semesterPeriods ?? []).map((period) => { const p = period.parameters ?? {}; return { ...emptySemester(period.year, period.semester), activeStudents: numberValue(p.activeStudents), graduatingStudents: numberValue(p.graduatingStudents), directTeachingHours: numberValue(p.directTeachingHours), replacementTeachingHours: numberValue(p.replacementTeachingHours), electiveSubjects: numberValue(p.electiveSubjects), electiveSections: numberValue(p.electiveSections), specializedCourses: numberValue(p.specializedCourses), specializedSections: numberValue(p.specializedSections), internalTuitionScholarshipStudents: numberValue(p.internalTuitionScholarshipStudents), internalTuitionScholarshipCoverage: numberValue(p.internalTuitionScholarshipCoverage ?? 1), maintenanceScholarshipStudents: numberValue(p.maintenanceScholarshipStudents), maintenanceScholarshipMonths: numberValue(p.maintenanceScholarshipMonths), notes: typeof p.notes === "string" ? p.notes : "" }; });
  const activeSemesters = semesters.length ? semesters : getActivePeriods(record.startYear, record.startSemester, record.durationSemesters).map((period, index) => ({ ...emptySemester(period.year, period.semester, record.initialStudents), graduatingStudents: index === record.durationSemesters - 1 ? record.initialStudents : 0 }));
  return { id: record.id, program: toProgram(record.program), cohortName: record.cohortName, startYear: record.startYear, startSemester: record.startSemester, durationSemesters: record.durationSemesters, initialStudents: record.initialStudents, status: budgetStatus(record.status), workflowStage: record.workflowStage, facultyOverheadRate: numberValue(record.facultyOverheadRate), enrollmentRecognitionRate: numberValue(record.enrollmentRecognitionRate), authorizedInitialCarryover: numberValue(record.authorizedInitialCarryover), includeAuthorizedCarryover: record.includeAuthorizedCarryover ?? true, normalizeSharedCosts: record.normalizeSharedCosts ?? true, alertPotentialDuplicates: record.alertPotentialDuplicates ?? true, appliedTemplateId: record.appliedTemplateId ?? undefined, appliedTemplateCode: record.appliedTemplate?.code, appliedTemplateVersion: record.appliedTemplateVersion ?? undefined, responsible: record.responsible?.name ?? "Gestión de Postgrado", version: record.versions?.[0]?.number ?? 1, createdAt: record.createdAt, updatedAt: record.updatedAt, notes: record.notes ?? undefined, semesters: activeSemesters,
    discounts: (record.discounts ?? []).map((item) => ({ id: String(item.id), name: String(item.name), percentage: numberValue(item.percentage), students: numberValue(item.students), startYear: numberValue(item.startYear), startSemester: numberValue(item.startSemester) as 1|2, endYear: numberValue(item.endYear), endSemester: numberValue(item.endSemester) as 1|2, note: typeof item.note === "string" ? item.note : undefined, originTemplateItemKey: typeof item.originTemplateItemKey === "string" ? item.originTemplateItemKey : undefined })),
    externalIncome: (record.externalIncome ?? []).map((item) => ({ id: String(item.id), type: String(item.type) as ExternalIncome["type"], description: String(item.description), year: numberValue(item.year), semester: numberValue(item.semester) as 1|2, students: numberValue(item.students), amountPerStudent: numberValue(item.amountPerStudent), source: String(item.source), note: typeof item.note === "string" ? item.note : undefined, originTemplateItemKey: typeof item.originTemplateItemKey === "string" ? item.originTemplateItemKey : undefined })),
    manualItems: (record.items ?? []).map((item) => ({ id: String(item.id), name: String(item.name), description: String(item.description), category: String(item.category) as BudgetItem["category"], year: numberValue(item.year), semester: item.semester == null ? undefined : numberValue(item.semester) as 1|2, amount: numberValue(item.amount), costType: item.costType === "COMPARTIDO" ? "Compartido con otras cohortes" : "Único de esta versión", periodicity: String(item.periodicity) as BudgetItem["periodicity"], note: typeof item.note === "string" ? item.note : undefined, originTemplateItemKey: typeof item.originTemplateItemKey === "string" ? item.originTemplateItemKey : undefined })),
    reviewHistory: (record.workflowEvents ?? []).map((event) => ({ id: event.id, role: event.role, decision: workflowDecision(event.action), user: event.user?.name ?? "Usuario institucional", comment: event.comment ?? undefined, createdAt: event.createdAt, fromStage: event.fromStage, toStage: event.toStage })),
  };
}
function freshBudget(program: Program, responsible: string): CohortBudget {
  const startYear = new Date().getFullYear() + 1; const periods = getActivePeriods(startYear, 1, program.officialDurationSemesters);
  return { ...clone(demoBudgets[0]), id: `draft-${Date.now()}`, program: clone(program), cohortName: `Nueva cohorte ${startYear}`, startYear, startSemester: 1, durationSemesters: program.officialDurationSemesters, status: "Borrador", workflowStage: "GESTION", facultyOverheadRate: overheadApplies(program.type) ? institutionalParameters.byProgramType[program.type].facultyOverheadRate : 0, authorizedInitialCarryover: 0, includeAuthorizedCarryover: true, normalizeSharedCosts: true, alertPotentialDuplicates: true, appliedTemplateId: undefined, appliedTemplateCode: undefined, appliedTemplateVersion: undefined, responsible, version: 1, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), reviewHistory: [], discounts: [], externalIncome: [], manualItems: [], semesters: periods.map((period, index) => ({ ...emptySemester(period.year, period.semester, 10), graduatingStudents: index === periods.length - 1 ? 10 : 0 })) };
}
const actionLabels: Record<WorkflowAction,string> = { SUBMIT_VB: "Enviar a visto bueno", VB_APPROVE: "Otorgar visto bueno", VB_OBSERVE: "Observar y devolver", FINAL_APPROVE: "Aprobar presupuesto", FINAL_OBSERVE: "Observar y devolver" };

export function BudgetWorkspace() {
  const [budgets, setBudgets] = useState<CohortBudget[]>(demoBudgets);
  const [programs, setPrograms] = useState<Program[]>(demoPrograms);
  const [templates, setTemplates] = useState<BudgetTemplate[]>(defaultBudgetTemplates);
  const [selectedId, setSelectedId] = useState(demoBudgets[0].id);
  const [role, setRole] = useState<AccessRole>("GESTOR");
  const [identity, setIdentity] = useState<ApiIdentity | null>(null);
  const [serverMode, setServerMode] = useState(false);
  const [message, setMessage] = useState("");

  useEffect(() => { Promise.all([fetch("/api/me",{cache:"no-store"}),fetch("/api/programs",{cache:"no-store"}),fetch("/api/budgets",{cache:"no-store"}),fetch("/api/templates",{cache:"no-store"})]).then(async ([me,p,b,t]) => {
    const identityResult = await responseBody<ApiIdentity>(me); const programRecords = await responseBody<ApiProgram[]>(p); const budgetRecords = await responseBody<ApiBudgetRecord[]>(b); const templateRecords = await responseBody<ApiTemplate[]>(t);
    const mappedPrograms = programRecords.map(toProgram); const mappedBudgets = budgetRecords.map(toBudget); const mappedTemplates = templateRecords.map((template) => ({...template, description: template.description ?? ""}));
    setIdentity(identityResult); setServerMode(true); setPrograms(mappedPrograms.length ? mappedPrograms : demoPrograms); setTemplates(mappedTemplates.length ? mappedTemplates : defaultBudgetTemplates); setRole(identityResult.roles[0] ?? "GESTOR"); if (mappedBudgets.length) { setBudgets(mappedBudgets); setSelectedId(mappedBudgets[0].id); }
  }).catch(() => { try { const saved = localStorage.getItem(STORAGE_KEY); if (saved) { const parsed = JSON.parse(saved) as CohortBudget[]; if (parsed.length) { setBudgets(parsed); setSelectedId(parsed[0].id); } } const templateSaved = localStorage.getItem(TEMPLATE_STORAGE_KEY); if (templateSaved) setTemplates(JSON.parse(templateSaved)); const savedRole = localStorage.getItem(ROLE_KEY) as AccessRole | null; if (savedRole) setRole(savedRole); } catch {} setServerMode(false); setMessage("Modo demostración local: los cambios se guardan en este navegador."); }); }, []);

  const budget = budgets.find((candidate) => candidate.id === selectedId) ?? budgets[0];
  const result = useMemo(() => calculateBudget(budget, institutionalParameters), [budget]);
  const editable = canEditBudget(budget, role);
  const scoped = programTypeParameters(institutionalParameters, budget.program.type);
  const workflowActions = availableWorkflowActions(budget.workflowStage, role);
  const duplicateAlerts = useMemo(() => budget.alertPotentialDuplicates ? detectPotentialDuplicateCosts(budgets, budget.id) : [], [budgets,budget]);
  const relevantTemplates = templates.filter((template) => template.active && template.programType === budget.program.type);
  const roleOptions: AccessRole[] = serverMode ? identity?.roles ?? [] : ["GESTOR","VISTO_BUENO","APROBADOR"];

  const replaceBudget = (next: CohortBudget) => setBudgets((current) => current.map((candidate) => candidate.id === next.id ? next : candidate));
  const updateHeader = <K extends keyof CohortBudget>(key: K, value: CohortBudget[K]) => { if (!editable) return; const next = {...budget,[key]:value,updatedAt:new Date().toISOString()}; if (["startYear","startSemester","durationSemesters","initialStudents"].includes(String(key))) { const existing = new Map(budget.semesters.map((semester)=>[`${semester.year}-${semester.semester}`,semester])); next.semesters = getActivePeriods(next.startYear,next.startSemester,next.durationSemesters).map((period,index)=>existing.get(`${period.year}-${period.semester}`) ?? {...emptySemester(period.year,period.semester,next.initialStudents),graduatingStudents:index===next.durationSemesters-1?next.initialStudents:0}); } replaceBudget(next); };
  const updateSemester = (index:number,key:keyof SemesterParameters,value:number|string) => editable && replaceBudget({...budget,semesters:budget.semesters.map((semester,candidate)=>candidate===index?{...semester,[key]:value}:semester)});
  const updateDiscount = (index:number,key:keyof CohortDiscount,value:string|number) => editable && replaceBudget({...budget,discounts:budget.discounts.map((item,candidate)=>candidate===index?{...item,[key]:value}:item)});
  const updateIncome = (index:number,key:keyof ExternalIncome,value:string|number) => editable && replaceBudget({...budget,externalIncome:budget.externalIncome.map((item,candidate)=>candidate===index?{...item,[key]:value}:item)});
  const updateCost = (index:number,key:keyof BudgetItem,value:string|number|undefined) => editable && replaceBudget({...budget,manualItems:budget.manualItems.map((item,candidate)=>candidate===index?{...item,[key]:value}:item)});
  const removeAt = (kind:"discount"|"income"|"cost",index:number) => { if (!editable) return; if (kind==="discount") replaceBudget({...budget,discounts:budget.discounts.filter((_,i)=>i!==index)}); if (kind==="income") replaceBudget({...budget,externalIncome:budget.externalIncome.filter((_,i)=>i!==index)}); if (kind==="cost") replaceBudget({...budget,manualItems:budget.manualItems.filter((_,i)=>i!==index)}); };
  const updateProgramTuition = (year:number,amount:number) => { if (!editable) return; const updated={...budget.program,tuitionSource:"PROPIO" as const,annualTuition:{...(budget.program.annualTuition??{}),[year]:Math.max(0,amount)}}; setPrograms((current)=>current.map((p)=>p.id===updated.id?clone(updated):p)); setBudgets((current)=>current.map((b)=>b.program.id===updated.id?{...b,program:clone(updated)}:b)); };

  async function saveAll() {
    if (!serverMode) { localStorage.setItem(STORAGE_KEY,JSON.stringify(budgets)); localStorage.setItem(TEMPLATE_STORAGE_KEY,JSON.stringify(templates)); localStorage.setItem(ROLE_KEY,role); setMessage("Cambios guardados en este navegador."); return; }
    const payload = { programId:budget.program.id,cohortName:budget.cohortName,startYear:budget.startYear,startSemester:budget.startSemester,durationSemesters:budget.durationSemesters,initialStudents:budget.initialStudents,facultyOverheadRate:budget.facultyOverheadRate,enrollmentRecognitionRate:budget.enrollmentRecognitionRate,authorizedInitialCarryover:budget.authorizedInitialCarryover,includeAuthorizedCarryover:budget.includeAuthorizedCarryover,normalizeSharedCosts:budget.normalizeSharedCosts,alertPotentialDuplicates:budget.alertPotentialDuplicates,appliedTemplateId:budget.appliedTemplateId??null,appliedTemplateVersion:budget.appliedTemplateVersion??null,notes:budget.notes,semesters:budget.semesters.map((semester,position)=>({...semester,position})),discounts:budget.discounts,externalIncome:budget.externalIncome,items:budget.manualItems,changeNote:"Ajuste de presupuesto" };
    await responseBody(await fetch(`/api/budgets/${budget.id}`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(payload)})); setMessage("Presupuesto y detalle guardados en Cloudflare D1.");
  }
  async function createBudget() { const next=freshBudget(programs.find((p)=>p.type==="MAGISTER_PROFESIONAL")??programs[0],identity?.name??"Gestión de Postgrado"); if (!serverMode) { setBudgets((c)=>[next,...c]); setSelectedId(next.id); return; } const created=await responseBody<ApiBudgetRecord>(await fetch("/api/budgets",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({programId:next.program.id,cohortName:next.cohortName,startYear:next.startYear,startSemester:next.startSemester,durationSemesters:next.durationSemesters,initialStudents:next.initialStudents,facultyOverheadRate:next.facultyOverheadRate,enrollmentRecognitionRate:next.enrollmentRecognitionRate,authorizedInitialCarryover:0,includeAuthorizedCarryover:true,normalizeSharedCosts:true,alertPotentialDuplicates:true,responsibleId:identity?.userId})})); setBudgets((c)=>[toBudget({...created,program:created.program??({} as ApiProgram)}),...c]); }
  async function deleteBudget() { if (!canDeleteBudget(budget,role) || !confirm(`¿Eliminar ${budget.program.code} · ${budget.cohortName}?`)) return; if (serverMode) await responseBody(await fetch(`/api/budgets/${budget.id}`,{method:"DELETE"})); const next=budgets.filter((candidate)=>candidate.id!==budget.id); setBudgets(next); setSelectedId(next[0]?.id??""); }
  async function executeWorkflow(action:WorkflowAction) { const next=applyWorkflowAction(budget,role,action,budget.responsible); if (serverMode) await responseBody(await fetch(`/api/budgets/${budget.id}/workflow`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action})})); replaceBudget(next); }

  return <div className="budget-workspace">
    {message ? <div className="notice success" role="status">{message}</div> : null}
    <section className="panel budget-selector"><div className="panel-header"><div><h2>Presupuestos creados</h2><p>Puede modificar o eliminar según el rol y la etapa.</p></div><button className="button primary" type="button" onClick={createBudget}>Nuevo presupuesto</button></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Programa y cohorte</th><th>Inicio</th><th>Estado</th><th>Acción</th></tr></thead><tbody>{budgets.map((item)=><tr key={item.id}><th>{item.program.code}<small>{item.cohortName}</small></th><td>{item.startYear}-{item.startSemester}S</td><td><StatusBadge status={item.status}/></td><td><button className="text-button" onClick={()=>setSelectedId(item.id)}>{item.id===budget.id?"Abierto":"Modificar"}</button></td></tr>)}</tbody></table></div></section>
    <div className="budget-actions"><div><StatusBadge status={budget.status}/><span>Etapa {budget.workflowStage} · Versión {budget.version}</span><label>Rol<select value={role} onChange={(event)=>setRole(event.target.value as AccessRole)}>{roleOptions.map((candidate)=><option key={candidate}>{candidate}</option>)}</select></label></div><div><button className="button secondary" onClick={()=>downloadBudgetXlsx(budget,result)}>Exportar XLSX</button><button className="button secondary" onClick={()=>downloadBudgetPdf(budget,result)}>Exportar PDF</button><button className="button secondary danger" onClick={deleteBudget}>Eliminar</button><button className="button primary" onClick={saveAll}>Guardar</button></div></div>

    <section className="panel"><SectionHeading number="1" id="identificacion" title="Identificación" description="Programa, cohorte, periodo y responsable."/><div className="form-grid"><label>Programa<select disabled={!editable} value={budget.program.id} onChange={(event)=>{const program=programs.find((p)=>p.id===event.target.value);if(program) updateHeader("program",clone(program));}}>{programs.map((p)=><option key={p.id} value={p.id}>{p.code} · {p.name}</option>)}</select></label><label>Cohorte<input disabled={!editable} value={budget.cohortName} onChange={(event)=>updateHeader("cohortName",event.target.value)}/></label><label>Año<input disabled={!editable} type="number" value={budget.startYear} onChange={(event)=>updateHeader("startYear",numberValue(event.target.value))}/></label><label>Semestre<select disabled={!editable} value={budget.startSemester} onChange={(event)=>updateHeader("startSemester",numberValue(event.target.value) as 1|2)}><option value="1">Primero</option><option value="2">Segundo</option></select></label><label>Duración<input disabled={!editable} type="number" min="2" max="8" value={budget.durationSemesters} onChange={(event)=>updateHeader("durationSemesters",numberValue(event.target.value))}/></label><label>Estudiantes iniciales<input disabled={!editable} type="number" min="0" value={budget.initialStudents} onChange={(event)=>updateHeader("initialStudents",numberValue(event.target.value))}/></label></div></section>

    <section className="panel"><SectionHeading number="2" id="parametros" title="Parámetros y plantilla" description="Arancel, arrastre, normalización y beneficios configurables." action={<a className="text-button" href="/parametros">Actualizar plantillas</a>}/><div className="tuition-focus"><div><span>Arancel propio del programa</span><strong>{formatCLP(result.annualFlows[0]?.annualTuition??0)}</strong></div><button className="button secondary" disabled={!editable} onClick={()=>{const updated={...budget.program,tuitionSource:"PLANTILLA_DOCTORADO" as const,annualTuition:Object.fromEntries(result.years.map((year)=>[year,institutionalParameters.doctorateTuitionTemplate[year]??0]))};setBudgets((current)=>current.map((b)=>b.program.id===updated.id?{...b,program:clone(updated)}:b));}}>Usar arancel plantilla doctoral</button></div><div className="parameter-grid tuition-grid">{result.years.map((year)=><label className="parameter-item editable" key={year}><span>Arancel {year}</span><input disabled={!editable} type="number" value={budget.program.annualTuition?.[year]??0} onChange={(event)=>updateProgramTuition(year,numberValue(event.target.value))}/></label>)}</div>
      <div className="template-grid">{relevantTemplates.map((template)=><article className={`template-card ${budget.appliedTemplateId===template.id?"selected":""}`} key={template.id}><span>{template.name}</span><p>{template.description}</p><small>Versión {template.version}</small><button className="button secondary" disabled={!editable} onClick={()=>replaceBudget(applyBudgetTemplate(budget,template))}>Usar plantilla</button></article>)}</div>
      <div className="setting-grid"><CheckSetting label="Incluir arrastre autorizado" note="Integra el monto en el primer año del flujo." checked={budget.includeAuthorizedCarryover} disabled={!editable} onChange={(value)=>updateHeader("includeAuthorizedCarryover",value)}/><CheckSetting label="Normalizar costos compartidos" note="Evita reconocer más de una vez el costo compartido." checked={budget.normalizeSharedCosts} disabled={!editable} onChange={(value)=>updateHeader("normalizeSharedCosts",value)}/><CheckSetting label="Alertar posibles duplicidades" note="Compara costos entre cohortes del mismo programa." checked={budget.alertPotentialDuplicates} disabled={!editable} onChange={(value)=>updateHeader("alertPotentialDuplicates",value)}/></div>
      <div className="parameter-grid"><label className="parameter-item editable"><span>Arrastre autorizado</span><input disabled={!editable||!budget.includeAuthorizedCarryover} type="number" value={budget.authorizedInitialCarryover} onChange={(event)=>updateHeader("authorizedInitialCarryover",numberValue(event.target.value))}/></label><div className="parameter-item"><span>Incobrabilidad</span><strong>{formatPercent(scoped.badDebtRate)}</strong></div><div className="parameter-item"><span>Overhead central</span><strong>{overheadApplies(budget.program.type)?formatPercent(scoped.centralOverheadRate):"No aplica"}</strong></div><div className="parameter-item"><span>Guía de tesis por estudiante</span><strong>{formatCLP(scoped.thesisGuidancePerGraduatingStudent[result.years[0]]??0)}</strong></div></div></section>

    <section className="panel"><SectionHeading number="3" id="estudiantes" title="Estudiantes, becas y graduación" description="Las becas de plantilla pueden ajustarse por semestre."/><div className="table-wrap"><table className="data-table compact-inputs"><thead><tr><th>Periodo</th><th>Activos</th><th>Graduación</th><th>Horas directas</th><th>Horas reemplazo</th><th>Beca arancel</th><th>Cobertura</th><th>Beca manutención</th><th>Meses</th></tr></thead><tbody>{budget.semesters.map((s,index)=><tr key={`${s.year}-${s.semester}`}><th>{s.year}-{s.semester}</th><InputCell label="Activos" value={s.activeStudents} disabled={!editable} onChange={(v)=>updateSemester(index,"activeStudents",v)}/><InputCell label="Graduación" value={s.graduatingStudents} disabled={!editable} onChange={(v)=>updateSemester(index,"graduatingStudents",v)}/><InputCell label="Horas directas" value={s.directTeachingHours} disabled={!editable} onChange={(v)=>updateSemester(index,"directTeachingHours",v)}/><InputCell label="Horas reemplazo" value={s.replacementTeachingHours} disabled={!editable} onChange={(v)=>updateSemester(index,"replacementTeachingHours",v)}/><InputCell label="Beca arancel" value={s.internalTuitionScholarshipStudents} disabled={!editable} onChange={(v)=>updateSemester(index,"internalTuitionScholarshipStudents",v)}/><InputCell label="Cobertura" value={s.internalTuitionScholarshipCoverage} step="0.1" disabled={!editable} onChange={(v)=>updateSemester(index,"internalTuitionScholarshipCoverage",v)}/><InputCell label="Beca manutención" value={s.maintenanceScholarshipStudents} disabled={!editable} onChange={(v)=>updateSemester(index,"maintenanceScholarshipStudents",v)}/><InputCell label="Meses" value={s.maintenanceScholarshipMonths} disabled={!editable} onChange={(v)=>updateSemester(index,"maintenanceScholarshipMonths",v)}/></tr>)}</tbody></table></div>{result.warnings.length?<div className="notice warning"><ul>{result.warnings.map((warning)=><li key={warning}>{warning}</li>)}</ul></div>:null}</section>

    <section className="panel"><SectionHeading number="4" id="descuentos" title="Descuentos" description="Agregue, modifique o quite descuentos por cantidad de estudiantes." action={<button className="button secondary" disabled={!editable} onClick={()=>{const periods=getActivePeriods(budget.startYear,budget.startSemester,budget.durationSemesters);replaceBudget({...budget,discounts:[...budget.discounts,{id:uid("discount"),name:"Nuevo descuento",percentage:0,students:0,startYear:periods[0].year,startSemester:periods[0].semester,endYear:periods.at(-1)!.year,endSemester:periods.at(-1)!.semester}]});}}>Agregar descuento</button>}/><div className="table-wrap"><table className="data-table editable-list"><thead><tr><th>Nombre</th><th>%</th><th>Estudiantes</th><th>Desde</th><th>Hasta</th><th>Acción</th></tr></thead><tbody>{budget.discounts.length?budget.discounts.map((d,index)=><tr key={d.id}><td><input disabled={!editable} value={d.name} onChange={(e)=>updateDiscount(index,"name",e.target.value)}/></td><td><input disabled={!editable} type="number" min="0" max="100" value={d.percentage*100} onChange={(e)=>updateDiscount(index,"percentage",numberValue(e.target.value)/100)}/></td><td><input disabled={!editable} type="number" value={d.students} onChange={(e)=>updateDiscount(index,"students",numberValue(e.target.value))}/></td><td><PeriodInputs year={d.startYear} semester={d.startSemester} years={result.years} disabled={!editable} onYear={(v)=>updateDiscount(index,"startYear",v)} onSemester={(v)=>updateDiscount(index,"startSemester",v)}/></td><td><PeriodInputs year={d.endYear} semester={d.endSemester} years={result.years} disabled={!editable} onYear={(v)=>updateDiscount(index,"endYear",v)} onSemester={(v)=>updateDiscount(index,"endSemester",v)}/></td><td><button className="text-button danger-text" disabled={!editable} onClick={()=>removeAt("discount",index)}>Quitar</button></td></tr>):<tr><td colSpan={6}>No hay descuentos configurados.</td></tr>}</tbody></table></div></section>

    <section className="panel"><SectionHeading number="5" id="ingresos" title="Ingresos extraordinarios" description="Becas externas, convenios, aportes y otros ingresos." action={<button className="button secondary" disabled={!editable} onClick={()=>replaceBudget({...budget,externalIncome:[...budget.externalIncome,{id:uid("income"),type:"Ingreso extraordinario",description:"Nuevo ingreso",year:result.years[0],semester:1,students:1,amountPerStudent:0,source:""}]})}>Agregar ingreso</button>}/><div className="table-wrap"><table className="data-table editable-list"><thead><tr><th>Tipo y descripción</th><th>Periodo</th><th>Estudiantes</th><th>Monto unitario</th><th>Fuente</th><th>Acción</th></tr></thead><tbody>{budget.externalIncome.length?budget.externalIncome.map((i,index)=><tr key={i.id}><td><select disabled={!editable} value={i.type} onChange={(e)=>updateIncome(index,"type",e.target.value)}>{INCOME_TYPES.map((type)=><option key={type}>{type}</option>)}</select><input disabled={!editable} value={i.description} onChange={(e)=>updateIncome(index,"description",e.target.value)}/></td><td><PeriodInputs year={i.year} semester={i.semester} years={result.years} disabled={!editable} onYear={(v)=>updateIncome(index,"year",v)} onSemester={(v)=>updateIncome(index,"semester",v)}/></td><td><input disabled={!editable} type="number" value={i.students} onChange={(e)=>updateIncome(index,"students",numberValue(e.target.value))}/></td><td><input disabled={!editable} type="number" value={i.amountPerStudent} onChange={(e)=>updateIncome(index,"amountPerStudent",numberValue(e.target.value))}/></td><td><input disabled={!editable} value={i.source} onChange={(e)=>updateIncome(index,"source",e.target.value)}/></td><td><button className="text-button danger-text" disabled={!editable} onClick={()=>removeAt("income",index)}>Quitar</button></td></tr>):<tr><td colSpan={6}>No hay ingresos extraordinarios.</td></tr>}</tbody></table></div></section>

    <section className="panel"><SectionHeading number="6" id="costos" title="Costos y gastos" description="Cada ítem puede ser único de esta versión o compartido con otras cohortes." action={<button className="button secondary" disabled={!editable} onClick={()=>replaceBudget({...budget,manualItems:[...budget.manualItems,{id:uid("cost"),name:"Nuevo costo",description:"",category:"Otros",year:result.years[0],amount:0,costType:"Único de esta versión",periodicity:"Único"}]})}>Agregar gasto o costo</button>}/><div className="table-wrap"><table className="data-table editable-list"><thead><tr><th>Nombre y descripción</th><th>Categoría</th><th>Año</th><th>Monto</th><th>Alcance</th><th>Periodicidad</th><th>Acción</th></tr></thead><tbody>{budget.manualItems.length?budget.manualItems.map((item,index)=><tr key={item.id}><td><input disabled={!editable} value={item.name} onChange={(e)=>updateCost(index,"name",e.target.value)}/><input disabled={!editable} value={item.description} onChange={(e)=>updateCost(index,"description",e.target.value)}/></td><td><select disabled={!editable} value={item.category} onChange={(e)=>updateCost(index,"category",e.target.value)}>{COST_CATEGORIES.map((category)=><option key={category}>{category}</option>)}</select></td><td><select disabled={!editable} value={item.year} onChange={(e)=>updateCost(index,"year",numberValue(e.target.value))}>{result.years.map((year)=><option key={year}>{year}</option>)}</select></td><td><input disabled={!editable} type="number" value={item.amount} onChange={(e)=>updateCost(index,"amount",numberValue(e.target.value))}/></td><td><select disabled={!editable} value={item.costType} onChange={(e)=>updateCost(index,"costType",e.target.value)}><option>Único de esta versión</option><option>Compartido con otras cohortes</option></select></td><td><select disabled={!editable} value={item.periodicity} onChange={(e)=>updateCost(index,"periodicity",e.target.value)}><option>Único</option><option>Semestral</option><option>Anual</option></select></td><td><button className="text-button danger-text" disabled={!editable} onClick={()=>removeAt("cost",index)}>Quitar</button></td></tr>):<tr><td colSpan={7}>No hay costos manuales.</td></tr>}</tbody></table></div>{budget.alertPotentialDuplicates?(duplicateAlerts.length?<div className="notice warning"><strong>Posibles duplicidades</strong><ul>{duplicateAlerts.map((alert)=><li key={alert.key}>{alert.message} {alert.allMarkedShared?"Se normalizará si la opción está activa.":"Revise el alcance."}</li>)}</ul></div>:<div className="notice success">No se detectaron coincidencias evidentes.</div>):null}</section>

    <section className="panel summary-panel"><SectionHeading number="7" id="resumen" title="Resumen financiero" description="Matrículas equivalentes y aproximación a estudiantes."/><div className="summary-grid"><div><span>Ingresos</span><strong>{formatCLP(result.annualFlows.reduce((a,f)=>a+f.totalIncome,0))}</strong></div><div><span>Egresos</span><strong>{formatCLP(result.annualFlows.reduce((a,f)=>a+f.totalExpenses,0))}</strong></div><div><span>Saldo final</span><strong>{formatCLP(result.finalAccumulatedFlow)}</strong></div><div><span>Viabilidad</span><strong>{result.viable===null?"Informativo":result.viable?"Viable":"No viable"}</strong></div></div><div className="equivalent-grid">{result.annualFlows.map((flow)=><div key={flow.year}><span>{flow.year}</span><strong>{flow.equivalentEnrollments.toLocaleString("es-CL",{maximumFractionDigits:1})} matrículas equivalentes</strong><small>≈ {flow.roundedEquivalentStudents} estudiantes</small></div>)}</div></section>

    <section className="panel"><SectionHeading number="8" id="flujo" title="Flujo de caja anual" description="Incluye descuentos, becas, ingresos extraordinarios y arrastre."/><div className="table-wrap financial-flow"><table className="data-table financial-table"><thead><tr><th>Concepto</th>{result.years.map((year)=><th className="numeric" key={year}>{year}</th>)}</tr></thead><tbody><FlowRow label="Matrícula" values={result.annualFlows.map((f)=>f.recognizedEnrollmentFee)} tone="income"/><FlowRow label="Arancel bruto" values={result.annualFlows.map((f)=>f.grossTuition)} tone="income"/><FlowRow label="Descuentos" values={result.annualFlows.map((f)=>-f.discounts)} tone="income"/><FlowRow label="Beca de excelencia académica" values={result.annualFlows.map((f)=>-f.internalTuitionScholarships)} tone="income"/><FlowRow label="Incobrables" values={result.annualFlows.map((f)=>-f.badDebt)} tone="income"/><FlowRow label="Ingresos extraordinarios" values={result.annualFlows.map((f)=>f.externalIncome)} tone="income"/><FlowRow label="INGRESOS TOTAL" values={result.annualFlows.map((f)=>f.totalIncome)} total tone="income"/><FlowRow label="COSTOS ACADÉMICOS" values={result.annualFlows.map((f)=>-f.academicHonoraria)} total/><FlowRow label="Honorarios no académicos" values={result.annualFlows.map((f)=>-f.nonAcademicHonoraria)}/><FlowRow label="Becas de manutención" values={result.annualFlows.map((f)=>-f.maintenanceScholarships)}/><FlowRow label="Dirección" values={result.annualFlows.map((f)=>-f.direction)}/><FlowRow label="Asistencia" values={result.annualFlows.map((f)=>-f.assistance)}/><FlowRow label="Overhead central" values={result.annualFlows.map((f)=>-f.centralOverhead)}/><FlowRow label="Overhead facultad" values={result.annualFlows.map((f)=>-f.facultyOverhead)}/><FlowRow label="TOTAL COSTOS Y GASTOS" values={result.annualFlows.map((f)=>-f.totalExpenses)} total tone="result"/><FlowRow label="FLUJO NETO" values={result.annualFlows.map((f)=>f.netFlow)} total tone="result" signed/><FlowRow label="Arrastre inicial anual" values={result.annualFlows.map((f)=>f.startingCarryover)} tone="result"/><FlowRow label="SALDO FINAL ACUMULADO" values={result.annualFlows.map((f)=>f.accumulatedFlow)} total tone="result" signed/></tbody></table></div></section>

    <section className="panel"><SectionHeading number="9" id="workflow" title="Revisión y aprobación" description="Gestor, V°B° y Aprobación."/><div className="workflow-actions">{workflowActions.length?workflowActions.map((transition)=><button key={transition.action} className="button primary" onClick={()=>executeWorkflow(transition.action)}>{actionLabels[transition.action]}</button>):<span>No hay acciones disponibles para este rol.</span>}</div></section>
  </div>;
}

function SectionHeading({number,id,title,description,action}:{number:string;id:string;title:string;description:string;action?:ReactNode}) { return <div className="section-heading"><div><span className="section-number">{number}</span><h2 id={id}>{title}</h2></div><div className="section-heading-action"><p>{description}</p>{action}</div></div>; }
function CheckSetting({label,note,checked,disabled,onChange}:{label:string;note:string;checked:boolean;disabled:boolean;onChange:(value:boolean)=>void}) { return <label className="setting-card"><input type="checkbox" checked={checked} disabled={disabled} onChange={(event)=>onChange(event.target.checked)}/><span><strong>{label}</strong><small>{note}</small></span></label>; }
function InputCell({label,value,onChange,disabled,step="1"}:{label:string;value:number;onChange:(value:number)=>void;disabled:boolean;step?:string}) { return <td><input aria-label={label} type="number" min="0" step={step} value={value} disabled={disabled} onChange={(event)=>onChange(numberValue(event.target.value))}/></td>; }
function PeriodInputs({year,semester,years,onYear,onSemester,disabled}:{year:number;semester:1|2;years:number[];onYear:(value:number)=>void;onSemester:(value:1|2)=>void;disabled:boolean}) { return <div className="period-inputs"><select disabled={disabled} value={year} onChange={(event)=>onYear(numberValue(event.target.value))}>{years.map((candidate)=><option key={candidate}>{candidate}</option>)}</select><select disabled={disabled} value={semester} onChange={(event)=>onSemester(numberValue(event.target.value) as 1|2)}><option value="1">1S</option><option value="2">2S</option></select></div>; }
function FlowRow({label,values,total=false,signed=false,tone=""}:{label:string;values:number[];total?:boolean;signed?:boolean;tone?:"income"|"result"|""}) { const resolved=tone||(total?"":"expense"); return <tr className={`${total?"row-total":""} ${resolved?`row-${resolved}`:""}`}><th>{label}</th>{values.map((value,index)=><td key={index} className={`numeric ${signed?(value>=0?"positive-text":"negative-text"):""}`}>{formatCLP(value)}</td>)}</tr>; }
