import test from "node:test";
import assert from "node:assert/strict";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../..");
const { applyProgramCurriculumToBudget }=await import(pathToFileURL(path.join(root,".engine-build/lib/curriculum/budget-load.js")).href);
const { demoBudget }=await import(pathToFileURL(path.join(root,".engine-build/lib/demo-data.js")).href);
function rng(seed=1211){let x=seed>>>0;return()=>{x=(1664525*x+1013904223)>>>0;return x/2**32}}
function c(id,kind,semester,weeks,sections,direct,autonomous,mode,factor){return{id,code:id,name:id,semester,kind,weeks,sections,theoryWeeklyHours:0,laboratoryWeeklyHours:0,workshopWeeklyHours:0,directWeeklyHours:direct,autonomousWeeklyHours:autonomous,teachingMode:mode,asynchronousRateFactor:factor,sharedWithProgramIds:[],allocationRate:1,sctCredits:0,position:0}}
test("v12.1.1: simulación masiva 2500 cohortes respeta secciones y excluye horas autónomas",()=>{const r=rng();const types=["DOCTORADO","MAGISTER_ACADEMICO","MAGISTER_PROFESIONAL"];const kinds=["OBLIGATORIA","ELECTIVA","ESPECIALIZACION","GRADUACION","COMPETENCIA_GENERICA"];for(let n=0;n<2500;n++){const type=types[Math.floor(r()*types.length)];const students=Math.floor(r()*41);const kind=kinds[Math.floor(r()*kinds.length)];const weeks=1+Math.floor(r()*24);const baseSections=1+Math.floor(r()*6);const direct=Math.round(r()*16)/2;const autonomous=Math.floor(r()*10000);const mode=r()<.25?"ASINCRONICA":"PRESENCIAL";const factor=Math.round(r()*100)/100;const course=c(`c${n}`,kind,1,weeks,baseSections,direct,autonomous,mode,factor);const b=structuredClone(demoBudget);b.program.type=type;b.program.curriculumCourses=[course];b.durationSemesters=2;b.semesters=b.semesters.slice(0,2).map(s=>({...s,activeStudents:students,directTeachingHours:0,synchronousTeachingHours:0,asynchronousTeachingHours:0}));b.deliveryModality="PRESENCIAL";const useOverride=r()<.45 && ["ELECTIVA","ESPECIALIZACION","GRADUACION"].includes(kind);const override=Math.floor(r()*12);b.curriculumSectionOverrides=useOverride?{[course.id]:override}:{};const out=applyProgramCurriculumToBudget(b);let sections;if(kind==="COMPETENCIA_GENERICA") sections=0;else if(useOverride) sections=override;else if(kind==="GRADUACION"&&(type==="DOCTORADO"||type==="MAGISTER_ACADEMICO")) sections=students;else sections=baseSections;let expected=kind==="COMPETENCIA_GENERICA"?0:weeks*sections*direct*(mode==="ASINCRONICA"?factor:1);const actual=mode==="ASINCRONICA"?out.semesters[0].asynchronousTeachingHours:out.semesters[0].directTeachingHours;assert.ok(Math.abs(actual-expected)<1e-9,JSON.stringify({n,type,kind,students,weeks,baseSections,direct,autonomous,mode,factor,useOverride,override,expected,actual}));}}
);
