import test from "node:test";
import assert from "node:assert/strict";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../..");
const mod=await import(pathToFileURL(path.join(root,".engine-build/lib/curriculum/budget-load.js")).href);
const { demoBudget }=await import(pathToFileURL(path.join(root,".engine-build/lib/demo-data.js")).href);
const { analyzeCurriculumMatrix }=await import(pathToFileURL(path.join(root,".engine-build/lib/import/curriculum-file-import.js")).href);
const { applyProgramCurriculumToBudget, curriculumCourseSectionsForBudget, curriculumCourseEffectiveHours }=mod;
function course(id,kind,semester=1,patch={}){return {id,code:id.toUpperCase(),name:id,semester,kind,weeks:18,sections:1,theoryWeeklyHours:0,laboratoryWeeklyHours:0,workshopWeeklyHours:0,directWeeklyHours:4,autonomousWeeklyHours:999,teachingMode:"PRESENCIAL",asynchronousRateFactor:.5,sharedWithProgramIds:[],allocationRate:1,sctCredits:4,position:0,...patch}}
function budget(type,courses,students=[10,10,10,10],overrides={}){const b=structuredClone(demoBudget);b.program.type=type;b.program.curriculumCourses=courses;b.durationSemesters=students.length;b.semesters=b.semesters.slice(0,students.length).map((s,i)=>({...s,activeStudents:students[i],directTeachingHours:0,synchronousTeachingHours:0,asynchronousTeachingHours:0}));b.curriculumSectionOverrides=overrides;b.deliveryModality="PRESENCIAL";return b}

test("v12.1.1: horas autónomas no alteran jamás la carga docente",()=>{const b=budget("MAGISTER_PROFESIONAL",[course("a","OBLIGATORIA",1,{directWeeklyHours:4,autonomousWeeklyHours:5000})],[12,12]);const r=applyProgramCurriculumToBudget(b);assert.equal(r.semesters[0].directTeachingHours,72);});
test("v12.1.1: tesis doctoral crea una sección por estudiante activo",()=>{const c=course("tesis1","GRADUACION",1,{sections:1,directWeeklyHours:2});const b=budget("DOCTORADO",[c],[13,13]);const r=applyProgramCurriculumToBudget(b);assert.equal(curriculumCourseSectionsForBudget(c,"DOCTORADO",13,{}),13);assert.equal(r.semesters[0].directTeachingHours,18*13*2);});
test("v12.1.1: AFE de magíster académico también sigue estudiantes",()=>{const c=course("afe","GRADUACION",2,{directWeeklyHours:1.5});const b=budget("MAGISTER_ACADEMICO",[c],[9,7]);const r=applyProgramCurriculumToBudget(b);assert.equal(r.semesters[1].directTeachingHours,18*7*1.5);});
test("v12.1.1: ajuste manual de tesis domina el automático",()=>{const c=course("tesis","GRADUACION",1,{directWeeklyHours:2});const b=budget("DOCTORADO",[c],[15,15],{tesis:3});const r=applyProgramCurriculumToBudget(b);assert.equal(r.semesters[0].directTeachingHours,18*3*2);});
test("v12.1.1: electivo permite varias secciones por cohorte",()=>{const c=course("electivo","ELECTIVA",1,{sections:2,directWeeklyHours:4});const b=budget("MAGISTER_PROFESIONAL",[c],[20,20],{electivo:5});const r=applyProgramCurriculumToBudget(b);assert.equal(r.semesters[0].directTeachingHours,18*5*4);});
test("v12.1.1: especialización permite varias secciones por cohorte",()=>{const c=course("esp","ESPECIALIZACION",1,{sections:2,directWeeklyHours:3});const b=budget("MAGISTER_PROFESIONAL",[c],[20,20],{esp:4});const r=applyProgramCurriculumToBudget(b);assert.equal(r.semesters[0].directTeachingHours,18*4*3);});
test("v12.1.1: obligatoria permanece en una sección aunque exista override",()=>{const c=course("obl","OBLIGATORIA",1,{sections:1,directWeeklyHours:4});const b=budget("MAGISTER_PROFESIONAL",[c],[20,20],{obl:8});const r=applyProgramCurriculumToBudget(b);assert.equal(r.semesters[0].directTeachingHours,72);});
test("v12.1.1: asincrónica aplica factor sólo sobre horas directas y secciones",()=>{const c=course("async","ELECTIVA",1,{directWeeklyHours:4,autonomousWeeklyHours:400,teachingMode:"ASINCRONICA",asynchronousRateFactor:.5});assert.equal(curriculumCourseEffectiveHours(c,"E_LEARNING",3),18*3*4*.5);});
test("v12.1.1: competencia genérica no genera costo",()=>{const c=course("gen","COMPETENCIA_GENERICA",1,{directWeeklyHours:12,autonomousWeeklyHours:30});const b=budget("MAGISTER_ACADEMICO",[c],[10,10]);const r=applyProgramCurriculumToBudget(b);assert.equal(r.semesters[0].directTeachingHours,0);});
test("v12.1.1: cero estudiantes implica cero secciones automáticas de tesis",()=>{const c=course("tesis0","GRADUACION",1,{directWeeklyHours:4});const b=budget("DOCTORADO",[c],[0,0]);const r=applyProgramCurriculumToBudget(b);assert.equal(curriculumCourseSectionsForBudget(c,"DOCTORADO",0,{}),0);assert.equal(r.semesters[0].directTeachingHours,0);});

test("v12.1.1: importador reconoce Tesis/AFE como graduación y descarta horas autónomas",()=>{const rows=[["Nivel (semestre)","Código","NOMBRE ASIGNATURA","Duración en semanas","Horas trabajo directo","Horas trabajo autónomo","Secciones"],[31,"TESI01","Tesis I",18,2,20,1],[32,"AFE02","Actividad Formativa Equivalente (AFE)",18,3,30,2]];const a=analyzeCurriculumMatrix(rows,"Plan");assert.ok(a);assert.equal(a.courses[0].kind,"GRADUACION");assert.equal(a.courses[1].kind,"GRADUACION");assert.equal(a.courses[0].autonomousWeeklyHours,0);assert.equal(a.courses[1].autonomousWeeklyHours,0);assert.equal(a.courses[1].sections,2);});
test("v12.1.1: tesis I y tesis II pueden usar estudiantes distintos por semestre",()=>{const courses=[course("tesisI","GRADUACION",1,{directWeeklyHours:1}),course("tesisII","GRADUACION",2,{directWeeklyHours:1.5})];const b=budget("MAGISTER_ACADEMICO",courses,[11,8]);const r=applyProgramCurriculumToBudget(b);assert.equal(r.semesters[0].directTeachingHours,18*11);assert.equal(r.semesters[1].directTeachingHours,18*8*1.5);});
