-- Mejoras funcionales v10: usuarios internos, roles ampliados, plantillas de arancel y parámetros editables.
PRAGMA foreign_keys = ON;

ALTER TABLE "User" ADD COLUMN "passwordHash" TEXT;
ALTER TABLE "User" ADD COLUMN "passwordSalt" TEXT;
ALTER TABLE "User" ADD COLUMN "passwordIterations" INTEGER;
ALTER TABLE "User" ADD COLUMN "passwordUpdatedAt" DATETIME;

ALTER TABLE "ProgramAnnualTuition" ADD COLUMN "templateType" TEXT;

CREATE TABLE IF NOT EXISTS "UserSession" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "userId" TEXT NOT NULL,
  "tokenHash" TEXT NOT NULL,
  "expiresAt" DATETIME NOT NULL,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS "UserSession_tokenHash_key" ON "UserSession"("tokenHash");
CREATE INDEX IF NOT EXISTS "UserSession_userId_idx" ON "UserSession"("userId");
CREATE INDEX IF NOT EXISTS "UserSession_expiresAt_idx" ON "UserSession"("expiresAt");

INSERT OR IGNORE INTO "Role" ("id", "code", "name", "description", "accessLevel") VALUES
  ('role-admin', 'ADMIN', 'Administrador', 'Administra usuarios, parámetros, programas y dispone de todos los permisos funcionales.', 'APROBADOR'),
  ('role-creador', 'CREADOR', 'Creador', 'Puede crear nuevos programas y presupuestos, sin intervenir en las etapas de aprobación.', 'GESTOR'),
  ('role-lector', 'LECTOR', 'Lector', 'Acceso de consulta sin permisos de modificación.', 'GESTOR');

INSERT OR IGNORE INTO "InstitutionalParameter" ("id", "code", "name", "unit", "annual", "editablePerBudget") VALUES
  ('param-tuition-template', 'TUITION_TEMPLATE', 'Plantilla de arancel por tipo de programa', 'CLP', true, false),
  ('param-planning-horizon', 'PLANNING_HORIZON', 'Horizonte de planificación', 'ANOS', false, false);

INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-direct_teaching_hour-2026','param-direct-hour',2026,'GENERAL',23152);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-direct_teaching_hour-2027','param-direct-hour',2027,'GENERAL',24310);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-direct_teaching_hour-2028','param-direct-hour',2028,'GENERAL',25526);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-direct_teaching_hour-2029','param-direct-hour',2029,'GENERAL',26802);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-direct_teaching_hour-2030','param-direct-hour',2030,'GENERAL',28142);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-maintenance_scholarship-2026','param-maintenance-scholarship',2026,'GENERAL',577500);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-maintenance_scholarship-2027','param-maintenance-scholarship',2027,'GENERAL',606375);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-maintenance_scholarship-2028','param-maintenance-scholarship',2028,'GENERAL',636694);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-maintenance_scholarship-2029','param-maintenance-scholarship',2029,'GENERAL',668529);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-maintenance_scholarship-2030','param-maintenance-scholarship',2030,'GENERAL',701956);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-annual_enrollment-2026','param-annual-enrollment',2026,'GENERAL',192150);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-annual_enrollment-2027','param-annual-enrollment',2027,'GENERAL',201758);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-annual_enrollment-2028','param-annual-enrollment',2028,'GENERAL',211846);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-annual_enrollment-2029','param-annual-enrollment',2029,'GENERAL',222439);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-annual_enrollment-2030','param-annual-enrollment',2030,'GENERAL',233561);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-replacement-hour-general','param-replacement-hour',NULL,'GENERAL',23152);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-adjustment-general','param-annual-adjustment',NULL,'GENERAL',0.05);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-planning-horizon-general','param-planning-horizon',NULL,'GENERAL',6);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-program_direction-doctorado-2026','param-program-direction',2026,'DOCTORADO',3954929);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-program_direction-doctorado-2027','param-program-direction',2027,'DOCTORADO',4152675);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-program_direction-doctorado-2028','param-program-direction',2028,'DOCTORADO',4360309);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-program_direction-doctorado-2029','param-program-direction',2029,'DOCTORADO',4578324);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-program_direction-doctorado-2030','param-program-direction',2030,'DOCTORADO',4807240);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-program_assistance-doctorado-2026','param-program-assistance',2026,'DOCTORADO',2000000);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-program_assistance-doctorado-2027','param-program-assistance',2027,'DOCTORADO',2100000);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-program_assistance-doctorado-2028','param-program-assistance',2028,'DOCTORADO',2205000);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-program_assistance-doctorado-2029','param-program-assistance',2029,'DOCTORADO',2315250);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-program_assistance-doctorado-2030','param-program-assistance',2030,'DOCTORADO',2431013);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-operating_expenses-doctorado-2026','param-operating-expenses',2026,'DOCTORADO',1800000);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-operating_expenses-doctorado-2027','param-operating-expenses',2027,'DOCTORADO',1890000);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-operating_expenses-doctorado-2028','param-operating-expenses',2028,'DOCTORADO',1984500);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-operating_expenses-doctorado-2029','param-operating-expenses',2029,'DOCTORADO',2083725);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-operating_expenses-doctorado-2030','param-operating-expenses',2030,'DOCTORADO',2187911);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-software_licenses-doctorado-2026','param-software-licenses',2026,'DOCTORADO',750000);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-software_licenses-doctorado-2027','param-software-licenses',2027,'DOCTORADO',787500);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-software_licenses-doctorado-2028','param-software-licenses',2028,'DOCTORADO',826875);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-software_licenses-doctorado-2029','param-software-licenses',2029,'DOCTORADO',868219);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-software_licenses-doctorado-2030','param-software-licenses',2030,'DOCTORADO',911630);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-diffusion_admission-doctorado-2026','param-diffusion-admission',2026,'DOCTORADO',1000000);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-diffusion_admission-doctorado-2027','param-diffusion-admission',2027,'DOCTORADO',1050000);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-diffusion_admission-doctorado-2028','param-diffusion-admission',2028,'DOCTORADO',1102500);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-diffusion_admission-doctorado-2029','param-diffusion-admission',2029,'DOCTORADO',1157625);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-diffusion_admission-doctorado-2030','param-diffusion-admission',2030,'DOCTORADO',1215506);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-thesis_guidance-doctorado-2026','param-thesis-guidance',2026,'DOCTORADO',250000);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-thesis_guidance-doctorado-2027','param-thesis-guidance',2027,'DOCTORADO',262500);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-thesis_guidance-doctorado-2028','param-thesis-guidance',2028,'DOCTORADO',275625);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-thesis_guidance-doctorado-2029','param-thesis-guidance',2029,'DOCTORADO',289406);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-thesis_guidance-doctorado-2030','param-thesis-guidance',2030,'DOCTORADO',303876);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-congresses-doctorado-2026','param-congresses-internships',2026,'DOCTORADO',22500000);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-congresses-doctorado-2027','param-congresses-internships',2027,'DOCTORADO',22500000);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-congresses-doctorado-2028','param-congresses-internships',2028,'DOCTORADO',22500000);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-congresses-doctorado-2029','param-congresses-internships',2029,'DOCTORADO',22500000);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-congresses-doctorado-2030','param-congresses-internships',2030,'DOCTORADO',22500000);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-central-overhead-doctorado','param-central-overhead',NULL,'DOCTORADO',0);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-faculty-overhead-doctorado','param-faculty-overhead',NULL,'DOCTORADO',0);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-bad-debt-doctorado','param-bad-debt',NULL,'DOCTORADO',0.15);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-tuition-template-doctorado-2026','param-tuition-template',2026,'DOCTORADO',4023852);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-tuition-template-doctorado-2027','param-tuition-template',2027,'DOCTORADO',4182884);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-tuition-template-doctorado-2028','param-tuition-template',2028,'DOCTORADO',4348182);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-tuition-template-doctorado-2029','param-tuition-template',2029,'DOCTORADO',4519991);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-tuition-template-doctorado-2030','param-tuition-template',2030,'DOCTORADO',4745991);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-program_direction-magister_academico-2026','param-program-direction',2026,'MAGISTER_ACADEMICO',3954929);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-program_direction-magister_academico-2027','param-program-direction',2027,'MAGISTER_ACADEMICO',4152675);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-program_direction-magister_academico-2028','param-program-direction',2028,'MAGISTER_ACADEMICO',4360309);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-program_direction-magister_academico-2029','param-program-direction',2029,'MAGISTER_ACADEMICO',4578324);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-program_direction-magister_academico-2030','param-program-direction',2030,'MAGISTER_ACADEMICO',4807240);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-program_assistance-magister_academico-2026','param-program-assistance',2026,'MAGISTER_ACADEMICO',2000000);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-program_assistance-magister_academico-2027','param-program-assistance',2027,'MAGISTER_ACADEMICO',2100000);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-program_assistance-magister_academico-2028','param-program-assistance',2028,'MAGISTER_ACADEMICO',2205000);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-program_assistance-magister_academico-2029','param-program-assistance',2029,'MAGISTER_ACADEMICO',2315250);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-program_assistance-magister_academico-2030','param-program-assistance',2030,'MAGISTER_ACADEMICO',2431013);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-operating_expenses-magister_academico-2026','param-operating-expenses',2026,'MAGISTER_ACADEMICO',1800000);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-operating_expenses-magister_academico-2027','param-operating-expenses',2027,'MAGISTER_ACADEMICO',1890000);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-operating_expenses-magister_academico-2028','param-operating-expenses',2028,'MAGISTER_ACADEMICO',1984500);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-operating_expenses-magister_academico-2029','param-operating-expenses',2029,'MAGISTER_ACADEMICO',2083725);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-operating_expenses-magister_academico-2030','param-operating-expenses',2030,'MAGISTER_ACADEMICO',2187911);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-software_licenses-magister_academico-2026','param-software-licenses',2026,'MAGISTER_ACADEMICO',750000);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-software_licenses-magister_academico-2027','param-software-licenses',2027,'MAGISTER_ACADEMICO',787500);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-software_licenses-magister_academico-2028','param-software-licenses',2028,'MAGISTER_ACADEMICO',826875);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-software_licenses-magister_academico-2029','param-software-licenses',2029,'MAGISTER_ACADEMICO',868219);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-software_licenses-magister_academico-2030','param-software-licenses',2030,'MAGISTER_ACADEMICO',911630);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-diffusion_admission-magister_academico-2026','param-diffusion-admission',2026,'MAGISTER_ACADEMICO',1000000);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-diffusion_admission-magister_academico-2027','param-diffusion-admission',2027,'MAGISTER_ACADEMICO',1050000);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-diffusion_admission-magister_academico-2028','param-diffusion-admission',2028,'MAGISTER_ACADEMICO',1102500);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-diffusion_admission-magister_academico-2029','param-diffusion-admission',2029,'MAGISTER_ACADEMICO',1157625);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-diffusion_admission-magister_academico-2030','param-diffusion-admission',2030,'MAGISTER_ACADEMICO',1215506);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-thesis_guidance-magister_academico-2026','param-thesis-guidance',2026,'MAGISTER_ACADEMICO',250000);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-thesis_guidance-magister_academico-2027','param-thesis-guidance',2027,'MAGISTER_ACADEMICO',262500);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-thesis_guidance-magister_academico-2028','param-thesis-guidance',2028,'MAGISTER_ACADEMICO',275625);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-thesis_guidance-magister_academico-2029','param-thesis-guidance',2029,'MAGISTER_ACADEMICO',289406);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-thesis_guidance-magister_academico-2030','param-thesis-guidance',2030,'MAGISTER_ACADEMICO',303876);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-congresses-magister_academico-2026','param-congresses-internships',2026,'MAGISTER_ACADEMICO',0);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-congresses-magister_academico-2027','param-congresses-internships',2027,'MAGISTER_ACADEMICO',0);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-congresses-magister_academico-2028','param-congresses-internships',2028,'MAGISTER_ACADEMICO',0);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-congresses-magister_academico-2029','param-congresses-internships',2029,'MAGISTER_ACADEMICO',0);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-congresses-magister_academico-2030','param-congresses-internships',2030,'MAGISTER_ACADEMICO',0);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-central-overhead-magister_academico','param-central-overhead',NULL,'MAGISTER_ACADEMICO',0);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-faculty-overhead-magister_academico','param-faculty-overhead',NULL,'MAGISTER_ACADEMICO',0);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-bad-debt-magister_academico','param-bad-debt',NULL,'MAGISTER_ACADEMICO',0.15);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-tuition-template-magister_academico-2026','param-tuition-template',2026,'MAGISTER_ACADEMICO',4023852);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-tuition-template-magister_academico-2027','param-tuition-template',2027,'MAGISTER_ACADEMICO',4182884);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-tuition-template-magister_academico-2028','param-tuition-template',2028,'MAGISTER_ACADEMICO',4348182);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-tuition-template-magister_academico-2029','param-tuition-template',2029,'MAGISTER_ACADEMICO',4519991);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-tuition-template-magister_academico-2030','param-tuition-template',2030,'MAGISTER_ACADEMICO',4745991);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-program_direction-magister_profesional-2026','param-program-direction',2026,'MAGISTER_PROFESIONAL',3954929);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-program_direction-magister_profesional-2027','param-program-direction',2027,'MAGISTER_PROFESIONAL',4152675);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-program_direction-magister_profesional-2028','param-program-direction',2028,'MAGISTER_PROFESIONAL',4360309);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-program_direction-magister_profesional-2029','param-program-direction',2029,'MAGISTER_PROFESIONAL',4578324);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-program_direction-magister_profesional-2030','param-program-direction',2030,'MAGISTER_PROFESIONAL',4807240);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-program_assistance-magister_profesional-2026','param-program-assistance',2026,'MAGISTER_PROFESIONAL',2000000);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-program_assistance-magister_profesional-2027','param-program-assistance',2027,'MAGISTER_PROFESIONAL',2100000);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-program_assistance-magister_profesional-2028','param-program-assistance',2028,'MAGISTER_PROFESIONAL',2205000);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-program_assistance-magister_profesional-2029','param-program-assistance',2029,'MAGISTER_PROFESIONAL',2315250);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-program_assistance-magister_profesional-2030','param-program-assistance',2030,'MAGISTER_PROFESIONAL',2431013);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-operating_expenses-magister_profesional-2026','param-operating-expenses',2026,'MAGISTER_PROFESIONAL',1800000);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-operating_expenses-magister_profesional-2027','param-operating-expenses',2027,'MAGISTER_PROFESIONAL',1890000);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-operating_expenses-magister_profesional-2028','param-operating-expenses',2028,'MAGISTER_PROFESIONAL',1984500);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-operating_expenses-magister_profesional-2029','param-operating-expenses',2029,'MAGISTER_PROFESIONAL',2083725);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-operating_expenses-magister_profesional-2030','param-operating-expenses',2030,'MAGISTER_PROFESIONAL',2187911);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-software_licenses-magister_profesional-2026','param-software-licenses',2026,'MAGISTER_PROFESIONAL',750000);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-software_licenses-magister_profesional-2027','param-software-licenses',2027,'MAGISTER_PROFESIONAL',787500);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-software_licenses-magister_profesional-2028','param-software-licenses',2028,'MAGISTER_PROFESIONAL',826875);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-software_licenses-magister_profesional-2029','param-software-licenses',2029,'MAGISTER_PROFESIONAL',868219);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-software_licenses-magister_profesional-2030','param-software-licenses',2030,'MAGISTER_PROFESIONAL',911630);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-diffusion_admission-magister_profesional-2026','param-diffusion-admission',2026,'MAGISTER_PROFESIONAL',1000000);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-diffusion_admission-magister_profesional-2027','param-diffusion-admission',2027,'MAGISTER_PROFESIONAL',1050000);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-diffusion_admission-magister_profesional-2028','param-diffusion-admission',2028,'MAGISTER_PROFESIONAL',1102500);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-diffusion_admission-magister_profesional-2029','param-diffusion-admission',2029,'MAGISTER_PROFESIONAL',1157625);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-diffusion_admission-magister_profesional-2030','param-diffusion-admission',2030,'MAGISTER_PROFESIONAL',1215506);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-thesis_guidance-magister_profesional-2026','param-thesis-guidance',2026,'MAGISTER_PROFESIONAL',250000);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-thesis_guidance-magister_profesional-2027','param-thesis-guidance',2027,'MAGISTER_PROFESIONAL',262500);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-thesis_guidance-magister_profesional-2028','param-thesis-guidance',2028,'MAGISTER_PROFESIONAL',275625);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-thesis_guidance-magister_profesional-2029','param-thesis-guidance',2029,'MAGISTER_PROFESIONAL',289406);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-thesis_guidance-magister_profesional-2030','param-thesis-guidance',2030,'MAGISTER_PROFESIONAL',303876);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-congresses-magister_profesional-2026','param-congresses-internships',2026,'MAGISTER_PROFESIONAL',0);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-congresses-magister_profesional-2027','param-congresses-internships',2027,'MAGISTER_PROFESIONAL',0);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-congresses-magister_profesional-2028','param-congresses-internships',2028,'MAGISTER_PROFESIONAL',0);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-congresses-magister_profesional-2029','param-congresses-internships',2029,'MAGISTER_PROFESIONAL',0);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-congresses-magister_profesional-2030','param-congresses-internships',2030,'MAGISTER_PROFESIONAL',0);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-central-overhead-magister_profesional','param-central-overhead',NULL,'MAGISTER_PROFESIONAL',0.2);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-faculty-overhead-magister_profesional','param-faculty-overhead',NULL,'MAGISTER_PROFESIONAL',0.1);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-bad-debt-magister_profesional','param-bad-debt',NULL,'MAGISTER_PROFESIONAL',0.15);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-tuition-template-magister_profesional-2026','param-tuition-template',2026,'MAGISTER_PROFESIONAL',4350000);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-tuition-template-magister_profesional-2027','param-tuition-template',2027,'MAGISTER_PROFESIONAL',4567500);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-tuition-template-magister_profesional-2028','param-tuition-template',2028,'MAGISTER_PROFESIONAL',4795875);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-tuition-template-magister_profesional-2029','param-tuition-template',2029,'MAGISTER_PROFESIONAL',5035669);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-tuition-template-magister_profesional-2030','param-tuition-template',2030,'MAGISTER_PROFESIONAL',5287452);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-program_direction-otro-2026','param-program-direction',2026,'OTRO',3954929);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-program_direction-otro-2027','param-program-direction',2027,'OTRO',4152675);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-program_direction-otro-2028','param-program-direction',2028,'OTRO',4360309);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-program_direction-otro-2029','param-program-direction',2029,'OTRO',4578324);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-program_direction-otro-2030','param-program-direction',2030,'OTRO',4807240);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-program_assistance-otro-2026','param-program-assistance',2026,'OTRO',2000000);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-program_assistance-otro-2027','param-program-assistance',2027,'OTRO',2100000);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-program_assistance-otro-2028','param-program-assistance',2028,'OTRO',2205000);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-program_assistance-otro-2029','param-program-assistance',2029,'OTRO',2315250);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-program_assistance-otro-2030','param-program-assistance',2030,'OTRO',2431013);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-operating_expenses-otro-2026','param-operating-expenses',2026,'OTRO',1800000);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-operating_expenses-otro-2027','param-operating-expenses',2027,'OTRO',1890000);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-operating_expenses-otro-2028','param-operating-expenses',2028,'OTRO',1984500);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-operating_expenses-otro-2029','param-operating-expenses',2029,'OTRO',2083725);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-operating_expenses-otro-2030','param-operating-expenses',2030,'OTRO',2187911);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-software_licenses-otro-2026','param-software-licenses',2026,'OTRO',750000);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-software_licenses-otro-2027','param-software-licenses',2027,'OTRO',787500);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-software_licenses-otro-2028','param-software-licenses',2028,'OTRO',826875);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-software_licenses-otro-2029','param-software-licenses',2029,'OTRO',868219);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-software_licenses-otro-2030','param-software-licenses',2030,'OTRO',911630);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-diffusion_admission-otro-2026','param-diffusion-admission',2026,'OTRO',1000000);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-diffusion_admission-otro-2027','param-diffusion-admission',2027,'OTRO',1050000);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-diffusion_admission-otro-2028','param-diffusion-admission',2028,'OTRO',1102500);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-diffusion_admission-otro-2029','param-diffusion-admission',2029,'OTRO',1157625);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-diffusion_admission-otro-2030','param-diffusion-admission',2030,'OTRO',1215506);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-thesis_guidance-otro-2026','param-thesis-guidance',2026,'OTRO',250000);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-thesis_guidance-otro-2027','param-thesis-guidance',2027,'OTRO',262500);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-thesis_guidance-otro-2028','param-thesis-guidance',2028,'OTRO',275625);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-thesis_guidance-otro-2029','param-thesis-guidance',2029,'OTRO',289406);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-thesis_guidance-otro-2030','param-thesis-guidance',2030,'OTRO',303876);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-congresses-otro-2026','param-congresses-internships',2026,'OTRO',0);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-congresses-otro-2027','param-congresses-internships',2027,'OTRO',0);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-congresses-otro-2028','param-congresses-internships',2028,'OTRO',0);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-congresses-otro-2029','param-congresses-internships',2029,'OTRO',0);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-congresses-otro-2030','param-congresses-internships',2030,'OTRO',0);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-central-overhead-otro','param-central-overhead',NULL,'OTRO',0.2);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-faculty-overhead-otro','param-faculty-overhead',NULL,'OTRO',0.1);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-bad-debt-otro','param-bad-debt',NULL,'OTRO',0.15);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-tuition-template-otro-2026','param-tuition-template',2026,'OTRO',0);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-tuition-template-otro-2027','param-tuition-template',2027,'OTRO',0);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-tuition-template-otro-2028','param-tuition-template',2028,'OTRO',0);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-tuition-template-otro-2029','param-tuition-template',2029,'OTRO',0);
INSERT OR REPLACE INTO "AnnualParameter" ("id","parameterId","year","scope","amount") VALUES ('annual-tuition-template-otro-2030','param-tuition-template',2030,'OTRO',0);
