import { z, ZodError } from "zod";
import { apiError, hasAnyAccess, requireApiIdentity } from "@/lib/auth/api-access";
import { d1Id, d1Json, runD1Batch } from "@/lib/database/d1-atomic";
import { getPrismaClient } from "@/lib/database/prisma";
import { d1Database } from "@/lib/runtime-env";
const intakeSchema=z.object({budgetId:z.string().min(1),windowId:z.string().optional().nullable(),label:z.string().trim().min(1).max(160),position:z.number().int().min(0).max(100).default(0),allocationRate:z.number().min(0).max(1).default(0)});
const costSchema=z.object({year:z.number().int().min(2000).max(2100),category:z.string().trim().min(1).max(120),name:z.string().trim().min(1).max(240),amount:z.number().int().nonnegative(),allocationMethod:z.enum(["INHERIT","EQUAL","STUDENTS","EQUIVALENT_ENROLLMENTS","MANUAL"]).default("INHERIT"),note:z.string().trim().max(600).optional().nullable()});
const schema=z.object({programId:z.string().min(1),year:z.number().int().min(2000).max(2100),name:z.string().trim().min(3).max(240),normalizeStaff:z.boolean().default(true),allocationMethod:z.enum(["EQUAL","STUDENTS","EQUIVALENT_ENROLLMENTS","MANUAL"]).default("EQUIVALENT_ENROLLMENTS"),notes:z.string().trim().max(2000).optional().nullable(),intakes:z.array(intakeSchema).min(1).max(24),sharedCosts:z.array(costSchema).max(100).default([])});
const json=(v:unknown)=>JSON.parse(JSON.stringify(v,(_,x)=>typeof x==="bigint"?x.toString():x));
async function validate(input:z.infer<typeof schema>){const prisma=getPrismaClient();const p=await prisma.program.findUnique({where:{id:input.programId},include:{intakeWindows:true}});if(!p)throw new Error("NOT_FOUND");if(p.type!=="MAGISTER_PROFESIONAL")throw new Error("ANNUAL_PLAN_PROFESSIONAL_ONLY");if(!p.annualPlanningEnabled)throw new Error("ANNUAL_PLAN_DISABLED");if(input.intakes.length>p.maxAnnualIntakes)throw new Error("ANNUAL_PLAN_MAX_INTAKES");const ids=[...new Set(input.intakes.map(i=>i.budgetId))];if(ids.length!==input.intakes.length)throw new Error("ANNUAL_PLAN_DUPLICATE_BUDGET");const bs=await prisma.cohortBudget.findMany({where:{id:{in:ids},deletedAt:null},select:{id:true,programId:true}});if(bs.length!==ids.length||bs.some(b=>b.programId!==input.programId))throw new Error("ANNUAL_PLAN_BUDGET_MISMATCH");const ws=new Set(p.intakeWindows.map(w=>w.id));if(input.intakes.some(i=>i.windowId&&!ws.has(i.windowId)))throw new Error("ANNUAL_PLAN_WINDOW_MISMATCH");}
export const dynamic="force-dynamic";
export async function GET(request:Request){try{await requireApiIdentity(request);const plans=await getPrismaClient().annualOfferingPlan.findMany({include:{program:{include:{intakeWindows:{orderBy:{displayOrder:"asc"}}}},intakes:{include:{window:true,budget:{select:{id:true,cohortName:true,startYear:true,startSemester:true,initialStudents:true,status:true}}},orderBy:{position:"asc"}},sharedCosts:{orderBy:[{year:"asc"},{name:"asc"}]}},orderBy:[{year:"desc"},{updatedAt:"desc"}]});return Response.json(json(plans))}catch(e){return apiError(e)}}
export async function POST(request:Request){try{const identity=await requireApiIdentity(request);if(!hasAnyAccess(identity,["CREADOR","GESTOR"]))throw new Error("FORBIDDEN");const input=schema.parse(await request.json());await validate(input);const prisma=getPrismaClient();const latest=await prisma.annualOfferingPlan.findFirst({where:{programId:input.programId,year:input.year},orderBy:{revision:"desc"},select:{revision:true}});const revision=(latest?.revision??0)+1,planId=d1Id("annual-plan"),db=d1Database();const st:D1PreparedStatement[]=[db.prepare(`INSERT INTO "AnnualOfferingPlan" ("id","programId","year","name","status","revision","normalizeStaff","allocationMethod","notes","createdAt","updatedAt") VALUES (?,?,?,?,'BORRADOR',?,?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)`).bind(planId,input.programId,input.year,input.name,revision,input.normalizeStaff?1:0,input.allocationMethod,input.notes??null)];for(const i of input.intakes)st.push(db.prepare(`INSERT INTO "AnnualOfferingPlanIntake" ("id","planId","budgetId","windowId","label","position","allocationRate","createdAt") VALUES (?,?,?,?,?,?,?,CURRENT_TIMESTAMP)`).bind(d1Id("annual-intake"),planId,i.budgetId,i.windowId??null,i.label,i.position,i.allocationRate));for(const c of input.sharedCosts)st.push(db.prepare(`INSERT INTO "AnnualOfferingPlanSharedCost" ("id","planId","year","category","name","amount","allocationMethod","note","createdAt","updatedAt") VALUES (?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)`).bind(d1Id("annual-cost"),planId,c.year,c.category,c.name,c.amount,c.allocationMethod,c.note??null));st.push(db.prepare(`INSERT INTO "AuditLog" ("id","userId","entity","entityId","action","newValue","createdAt") VALUES (?,?,'AnnualOfferingPlan',?,'CREATE_ANNUAL_PLAN',?,CURRENT_TIMESTAMP)`).bind(d1Id("audit"),identity.userId,planId,d1Json(input)));await runD1Batch(st);const created=await prisma.annualOfferingPlan.findUnique({where:{id:planId},include:{program:{include:{intakeWindows:true}},intakes:{include:{window:true,budget:true},orderBy:{position:"asc"}},sharedCosts:true}});return Response.json(json(created),{status:201})}catch(e){if(e instanceof ZodError)return Response.json({error:"Datos del plan anual inválidos.",issues:e.issues},{status:400});return apiError(e)}}
