import { calculateBudget } from "../calculations/budget-engine";
import type { BudgetResult, CohortBudget, InstitutionalParameters } from "../calculations/types";

export type AllocationMethod = "EQUAL" | "STUDENTS" | "EQUIVALENT_ENROLLMENTS" | "MANUAL";
export interface AnnualPlanSharedCostInput { id?: string; year: number; category: string; name: string; amount: number; allocationMethod?: AllocationMethod | "INHERIT"; note?: string; }
export interface AnnualPlanIntakeInput { id?: string; label: string; budget: CohortBudget; allocationRate?: number; position?: number; }
export interface AnnualOfferingPlanInput { id?: string; programId: string; year: number; name: string; normalizeStaff: boolean; allocationMethod: AllocationMethod; intakes: AnnualPlanIntakeInput[]; sharedCosts: AnnualPlanSharedCostInput[]; }
export interface AnnualPlanIntakeResult { id:string; label:string; budgetId:string; cohortName:string; initialStudents:number; equivalentEnrollments:number; totalIncome:number; totalExpensesBeforePlanAdjustments:number; totalExpenses:number; finalResult:number; margin:number|null; viable:boolean; result:BudgetResult; }
export interface AnnualPlanYearResult { year:number; totalIncome:number; academicHonoraria:number; staffBeforeNormalization:number; staffAfterNormalization:number; staffSavings:number; otherExpenses:number; equipment:number; scholarshipsAndAid:number; overhead:number; sharedProgramCosts:number; totalExpenses:number; netFlow:number; accumulatedFlow:number; }
export interface AnnualPlanScenario { count:number; label:string; budgetIds:string[]; students:number; equivalentEnrollments:number; totalIncome:number; totalExpenses:number; finalResult:number; margin:number|null; viable:boolean; }
export interface AnnualPlanBreakEven { currentEquivalentEnrollments:number; minimumEquivalentEnrollments:number; approximateFullTuitionStudents:number; scaleFactor:number; suggestedByIntake:Array<{label:string;equivalentEnrollments:number}>; note:string; }
export interface AnnualOfferingPlanResult { intakes:AnnualPlanIntakeResult[]; years:AnnualPlanYearResult[]; scenarios:AnnualPlanScenario[]; breakEven:AnnualPlanBreakEven; totalStudents:number; totalEquivalentEnrollments:number; totalIncome:number; totalExpenses:number; finalResult:number; margin:number|null; viable:boolean; }
const sum=(v:number[])=>v.reduce((a,b)=>a+b,0);
function normalizedStaff(flows:Array<{direction:number;assistance:number;otherNonAcademicHonoraria:number}>, enabled:boolean){const before=sum(flows.map(f=>f.direction+f.assistance+f.otherNonAcademicHonoraria));if(!enabled||flows.length<=1)return{before,after:before,savings:0};const after=Math.max(0,...flows.map(f=>f.direction))+Math.max(0,...flows.map(f=>f.assistance))+Math.max(0,...flows.map(f=>f.otherNonAcademicHonoraria));return{before,after,savings:Math.max(0,before-after)}}
export function calculateAnnualOfferingPlan(plan:AnnualOfferingPlanInput,parameters:InstitutionalParameters):AnnualOfferingPlanResult{
 if(!plan.intakes.length)throw new Error("El plan anual debe contener al menos una cohorte.");
 if(plan.intakes.some(i=>i.budget.program.id!==plan.programId))throw new Error("Todas las cohortes del plan deben pertenecer al mismo programa.");
 if(plan.intakes.some(i=>i.budget.program.type!=="MAGISTER_PROFESIONAL"))throw new Error("La planificación anual sólo está disponible para Magísteres Profesionales.");
 const computed=plan.intakes.map((intake,index)=>({intake,index,result:calculateBudget(intake.budget,parameters)}));
 const years=[...new Set(computed.flatMap(x=>x.result.years).concat(plan.sharedCosts.map(x=>x.year)))].sort((a,b)=>a-b);let accumulated=0;
 const yearResults:AnnualPlanYearResult[]=years.map(year=>{const flows=computed.flatMap(x=>x.result.annualFlows.filter(f=>f.year===year));const income=sum(flows.map(f=>f.totalIncome));const academic=sum(flows.map(f=>f.academicHonoraria));const staff=normalizedStaff(flows,plan.normalizeStaff);const other=sum(flows.map(f=>f.otherExpenses));const equipment=sum(flows.map(f=>f.equipment));const scholarships=sum(flows.map(f=>f.scholarshipsAndAid));const overhead=sum(flows.map(f=>f.centralOverhead+f.facultyOverhead));const shared=sum(plan.sharedCosts.filter(c=>c.year===year).map(c=>Math.max(0,c.amount)));const expenses=academic+staff.after+other+equipment+scholarships+overhead+shared;const net=income-expenses;accumulated+=net;return{year,totalIncome:income,academicHonoraria:academic,staffBeforeNormalization:staff.before,staffAfterNormalization:staff.after,staffSavings:staff.savings,otherExpenses:other,equipment,scholarshipsAndAid:scholarships,overhead,sharedProgramCosts:shared,totalExpenses:expenses,netFlow:net,accumulatedFlow:accumulated}});
 const totalIncome=sum(yearResults.map(x=>x.totalIncome)), totalExpenses=sum(yearResults.map(x=>x.totalExpenses)), finalResult=totalIncome-totalExpenses, totalEq=sum(computed.flatMap(x=>x.result.annualFlows.map(f=>f.equivalentEnrollments))), totalStudents=sum(computed.map(x=>Math.max(0,x.intake.budget.initialStudents)));
 const weights=computed.map(({intake,result})=>plan.allocationMethod==="EQUAL"?1:plan.allocationMethod==="STUDENTS"?Math.max(0,intake.budget.initialStudents):plan.allocationMethod==="MANUAL"?Math.max(0,intake.allocationRate??0):sum(result.annualFlows.map(f=>f.equivalentEnrollments)));const weightTotal=sum(weights)||computed.length;const staffSavings=sum(yearResults.map(x=>x.staffSavings)), sharedCosts=sum(plan.sharedCosts.map(x=>Math.max(0,x.amount)));
 const intakes:AnnualPlanIntakeResult[]=computed.map(({intake,result},index)=>{const income=sum(result.annualFlows.map(f=>f.totalIncome));const before=sum(result.annualFlows.map(f=>f.totalExpenses));const weight=(weights[index]||(weightTotal===computed.length?1:0))/weightTotal;const expenses=Math.max(0,before-staffSavings*weight+sharedCosts*weight);const res=income-expenses;return{id:intake.id??intake.budget.id,label:intake.label,budgetId:intake.budget.id,cohortName:intake.budget.cohortName,initialStudents:intake.budget.initialStudents,equivalentEnrollments:sum(result.annualFlows.map(f=>f.equivalentEnrollments)),totalIncome:income,totalExpensesBeforePlanAdjustments:before,totalExpenses:expenses,finalResult:res,margin:income>0?res/income:null,viable:res>=0,result}});
 const revenuePerEq=totalEq>0?totalIncome/totalEq:0;const minEq=revenuePerEq>0?totalExpenses/revenuePerEq:0;const scale=totalEq>0?minEq/totalEq:0;const breakEven={currentEquivalentEnrollments:totalEq,minimumEquivalentEnrollments:minEq,approximateFullTuitionStudents:Math.ceil(minEq),scaleFactor:scale,suggestedByIntake:intakes.map(x=>({label:x.label,equivalentEnrollments:totalEq>0?x.equivalentEnrollments*scale:0})),note:"Estimación proporcional del umbral anual; distintas combinaciones de matrícula entre inicios pueden alcanzar el mismo equilibrio."};
 const scenarios:AnnualPlanScenario[]=[];for(let count=1;count<=plan.intakes.length;count++){const subset=plan.intakes.slice(0,count);const sub=subset.map(intake=>({intake,result:calculateBudget(intake.budget,parameters)}));const flows=sub.flatMap(x=>x.result.annualFlows);const income=sum(flows.map(f=>f.totalIncome));const academic=sum(flows.map(f=>f.academicHonoraria));let staff=0;for(const y of [...new Set(flows.map(f=>f.year))])staff+=normalizedStaff(flows.filter(f=>f.year===y),plan.normalizeStaff).after;const other=sum(flows.map(f=>f.otherExpenses+f.equipment+f.scholarshipsAndAid+f.centralOverhead+f.facultyOverhead));const expenses=academic+staff+other+sharedCosts;const res=income-expenses;scenarios.push({count,label:subset.map(x=>x.label).join(" + "),budgetIds:subset.map(x=>x.budget.id),students:sum(subset.map(x=>x.budget.initialStudents)),equivalentEnrollments:sum(sub.flatMap(x=>x.result.annualFlows.map(f=>f.equivalentEnrollments))),totalIncome:income,totalExpenses:expenses,finalResult:res,margin:income>0?res/income:null,viable:res>=0})}
 return{intakes,years:yearResults,scenarios,breakEven,totalStudents,totalEquivalentEnrollments:totalEq,totalIncome,totalExpenses,finalResult,margin:totalIncome>0?finalResult/totalIncome:null,viable:finalResult>=0};
}
